{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kriging
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kriging_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kriging/kriging_{{ version }}.tar.gz
  sha256: c8238db37ba0efba2ec874a25b5738a0fa554800606b08486e94838710db0ce9

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('kriging')"           # [not win]
    - "\"%R%\" -e \"library('kriging')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=kriging
  license: GPL-2.0-only
  summary: Simple and highly optimized ordinary kriging algorithm to plot geographical data
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: kriging
# Version: 1.1
# License: GPL-2
# Description: Simple and highly optimized ordinary kriging algorithm to plot geographical data
# Title: Ordinary Kriging
# Author: Omar E. Olmedo
# Maintainer: Omar E. Olmedo <omareolmedo@gmail.com>
# Suggests: maps
# Packaged: 2014-12-01 15:38:27 UTC; oolmedo
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-12-01 17:55:32
