appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kMmNl+bu2Z7b8+2UMqvTLOYEEU/zpdOAEfh4jWEwH9aMb8s1vlWE9aP8nCE5p9WeTtQ9K2nU7UztdVQAOczY6RE1wENoiECGFIpKKQqn3hSkV7GSqnCjgo0NrvrqcXbrGxGpkvuA2HbPFVYTVNUd958aLd88ICeYHrKmNrTsJbD1pSPskW6LpntK0g/Lm1NZVQ1Do6fbO0mu/Jgt8TuFt/hslGkFUZN4lsBYV4ZJHOW1190klftFm3MOkTtMdhSC4UTCv5QBaIK7MziUm4EJio54bAF1z9TKw3w9WmK0+Wz7kDwE7I7xHUe+hPHWXN9++iYcChe+Eb5Vr2ojTKxHUFGKUQBCpoxzFXAI4VijdOYbohyIgTppXzGDW7XJUDb3SPN94gRXbaxGNgew80LEarXgEzz5U0Yri5XqzHv8fqVEUb+3un2D57JzDvCnkhWh0Sls24zEoUz+93VPrgsY46e/rDXTU+gf5pg4HwYGfvkfNJ6W4oO+s2qLUQzkydgV1ZkW5Ijy6R4J5hF3UaCVJYXZk4MiRSfQ0Qd/bJDvxMRkhj+Poe4Yh/gdMeLCukuaFLRVuSwhEiuZhPBxGi+vH7hvHUmKN/X+htwIkOqG5KavIGSUewABlwVpYuEGxJSA4H6mw9736yC5GW2pGvxsqaHZm9+rS4ocF5ivKxj3R3U=}
